#  ------------------------------
# |        HuskChat Config      |
# |    Developed by William278  |
#  ------------------------------
# Configuration guide: https://github.com/WiIIiam278/HuskChat/wiki
# To modify individual message locales, see the messages file.

# General options. Default channel should match one of the channels below.
language: 'en-gb'
default_channel: global
channel_log_format: '[CHAT] [%channel%] %sender%: %message%'

# Chat channel configuration.
# - You can edit the default channels and make your own if you would like.
# - Channels that have permissions set require them to send and receive messages respectively.
channels:
  local:
    format: '%fullname%&r&f: '
    broadcast_scope: LOCAL
    log_to_console: true
    shortcut_commands:
      - /local
      - /l
  global:
    format: '&#00fb9a&[G]&r&f %fullname%&r&f: '
    broadcast_scope: GLOBAL
    log_to_console: true
    shortcut_commands:
      - /global
      - /g
    #restricted_servers: # Set where it is not possible to use this channel
    #  - minigame
  staff:
    format: '&e[Staff] %name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    permissions:
      send: 'huskchat.channel.staff.send'
      receive: 'huskchat.channel.staff.receive'
    shortcut_commands:
      - /staff
      - /sc
  helpop:
    format: '&#00fb9a&[HelpOp] %name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    permissions:
      receive: 'huskchat.channel.helpop.receive'
    shortcut_commands:
      - /helpop
      - /helpme

# Server Default Channel Configuration
# - Set a channel that the player will automatically be set to when changing servers
# - Players will still be able to switch channels and use /msg and /r unless you add servers to the restricted_servers list
#server_default_channels:
#  minigame: local

# Options for the /msg and /r commands
message_command:
  enabled: true
  log_to_console: true
  log_format: '[MSG] [%sender% -> %receiver%]: %message%'
  format:
    inbound: '&#00fb9a&%name% &8→ &#00fb9a&You&8: &f'
    outbound: '&#00fb9a&You &8→ &#00fb9a&%name%&8: &f'
  #restricted_servers: # Set where /msg and /r cannot be used
  #  - hub

# Options for the /socialspy command
social_spy:
  enabled: true
  format: '&e[Spy] &7%sender_name% &8→ &7%receiever_name%:%spy_color% '

# Options for the /localspy command
local_spy:
  enabled: true
  format: '&e[Spy] &7[%channel%] %name%&8:%spy_color% '
  #excluded_local_channels: # Channels to exclude from local spying
  #  - local