name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Python
      uses: actions/setup-python@v2.3.2
    - name: Install packages
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install jep
        python -m pip install alt-profanity-check
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build --args='--java.library.path=/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jep/'
